version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - money_network
    ports:
      - "8080:8080"

  db:
    image: mysql:8.0
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: money_manager
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - money_network

volumes:
  db:

networks:
  money_network:
